export const orderConstants = {
  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",

  MY_ORDERS_REQUEST: "MY_ORDERS_REQUEST",
  MY_ORDERS_SUCCESS: "MY_ORDERS_SUCCESS",
  MY_ORDERS_FAIL: "MY_ORDERS_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
